Pr9
IvanFadieiev/BookStore pull request #10
Opened 2023-09-23 16:07 UTC by IvanFadieiev

2023-09-25 09:21 UTC, OlegTuryk commented on src/main/java/project/bookstore/model/Order.java
> +    private Set<OrderItem> orderItems = new HashSet<>();
You can add Cascade.Persist. It will save orderItems when you save order authomatically

2023-09-25 09:22 UTC, OlegTuryk commented on src/main/java/project/bookstore/repository/OrderRepository.java
> +    Optional<Order> getOrderById(Long id);
I think you can have here lazyInitializationException, that why If you want add here join fetch

2023-09-25 09:24 UTC, OlegTuryk commented on src/main/resources/db/changelog/changes/15-create-orders-table.yaml
> +                    nullable: false
add FK

2023-09-25 09:26 UTC, OlegTuryk requested changes

2023-09-25 09:26 UTC, OlegTuryk commented on src/main/resources/db/changelog/changes/16-create-order-items-table.yaml
> +                    nullable: false
here to

2023-09-25 09:26 UTC, OlegTuryk commented on src/main/java/project/bookstore/service/impl/OrderServiceImpl.java
> +        order.setShippingAddress(orderRequestDto.shippingAddress());
You can use mapper to convert shoppingCart and OrderCreateRequestDto to Order

2023-09-25 10:24 UTC, IvanFadieiev commented on src/main/java/project/bookstore/repository/OrderRepository.java
> +    Optional<Order> getOrderById(Long id);
@OlegTuryk according to my realization of fillOrder method it's impossible that i would have LazyInitializationException. All my order's fields initialized at the moment of creating of order.

2023-09-25 10:25 UTC, IvanFadieiev commented on src/main/java/project/bookstore/service/impl/OrderServiceImpl.java
> +        order.setShippingAddress(orderRequestDto.shippingAddress());
@OlegTuryk I prefer to do it with private method in orderServiceImpl, I'll let this mentor to decide :)

2023-09-25 10:27 UTC, OlegTuryk commented on src/main/java/project/bookstore/repository/OrderRepository.java
> +    Optional<Order> getOrderById(Long id);
You can get it when you try to get data from db

2023-09-25 12:06 UTC, IvanFadieiev commented on src/main/java/project/bookstore/repository/OrderRepository.java
> +    Optional<Order> getOrderById(Long id);
resolved in Slack DM

2023-09-26 15:09 UTC, vovasalyha approved these changes
GJ

2023-10-09 16:46 UTC, merged