Pr11 tests part1
IvanFadieiev/BookStore pull request #12
Opened 2023-09-29 07:01 UTC by IvanFadieiev

2023-10-09 11:20 UTC, Zel1oy approved these changes
GJ

2023-10-09 13:32 UTC, andrii-hoienko requested changes
GJ! Let`s improve your solution

2023-10-09 13:32 UTC, andrii-hoienko commented on src/test/java/project/bookstore/controller/BookControllerTest.java
> +        Assertions.assertNotNull(actual);
Please use static import

2023-10-09 13:32 UTC, andrii-hoienko commented on src/test/java/project/bookstore/service/BookServiceTest.java
> +        Mockito.when(bookMapper.toModel(BOOK_REQUEST_DTO)).thenReturn(BOOK);
static import

2023-10-09 13:32 UTC, andrii-hoienko commented on src/test/java/project/bookstore/service/BookServiceTest.java
> +        BookDtoWithoutCategoryIds bookDtoWithoutCategoryIds
Please all object creation code outside a method

2023-10-09 13:32 UTC, andrii-hoienko commented on src/test/resources/database/scripts/books/add-book-to-books-table.sql
> +VALUES (1, 'Meditations', 'Marcus Aurelius', '978-4-2596-7831-9', 1000, 'Description', 'Cover image', false);
add empty lines

2023-10-16 15:22 UTC, vovasalyha approved these changes

2023-10-16 15:23 UTC, merged