Readme
IvanFadieiev/BookStore pull request #13
Opened 2023-09-29 16:00 UTC by IvanFadieiev

2023-10-05 12:31 UTC, andrii-hoienko requested changes
GJ! But still, some improvements required

2023-10-05 12:31 UTC, andrii-hoienko commented on Readme.md
> +As an authorized user you can:
rewrite it mentioning controllers functionality

2023-10-05 12:31 UTC, andrii-hoienko commented on Readme.md
> +![Banner](banner.jpg)
Please add loom video

2023-10-05 12:31 UTC, andrii-hoienko commented on Readme.md
> +- SpringBoot
Add details about purpose of tools you used

2023-10-05 12:31 UTC, andrii-hoienko commented on Readme.md
> +### Installation
Add guide for alternative way to run app

2023-10-05 12:31 UTC, andrii-hoienko commented on Readme.md
> +### Installation
What tools required to run app?

2023-10-05 12:31 UTC, andrii-hoienko commented on Readme.md
> +### Postman requests collection
Tell something about Contributing

2023-10-05 12:31 UTC, andrii-hoienko commented on Readme.md
> +### Functionalities
mention security and validations rules

2023-10-19 10:27 UTC, andrii-hoienko commented on Readme.md
> +### Installation
It is not enough to just have a docker

2023-10-19 10:28 UTC, andrii-hoienko commented on Readme.md
> +### Installation
Not resolved, by an alternative way I mean start app without docker (using java only)

2023-10-19 10:28 UTC, andrii-hoienko requested changes
Some comments are not resolved

2023-10-19 14:49 UTC, vovasalyha approved these changes

2023-10-19 14:53 UTC, merged