Pr13 tests
IvanFadieiev/BookStore pull request #14
Opened 2023-10-20 12:29 UTC by IvanFadieiev

2023-10-20 16:01 UTC, OlegTuryk approved these changes

2023-10-23 15:28 UTC, vovasalyha requested changes
GJ, but see a couple of comments

2023-10-23 15:28 UTC, vovasalyha commented on src/test/java/project/bookstore/repository/CartItemRepositoryTest.java
> +            "classpath:database/scripts/books/clear-books-table.sql",
You have created constants for scripts in previous class, but here it is hardcoded. Try to be consistent.

2023-10-23 15:28 UTC, vovasalyha commented on src/test/java/project/bookstore/service/ShoppingCartServiceTest.java
> +        verify(shoppingCartMapper, Mockito.times(1))
times(1) is default, so you don't need to specify this parameter. Additionally, using verify on stabbed method calls is redundant, you can check `verify` method documentation.

2023-10-23 15:28 UTC, vovasalyha commented on src/test/java/project/bookstore/service/ShoppingCartServiceTest.java
> +    public void getShoppingCart_ThrowsException() {
Ambiguous name. When should it throw an exception?

2023-10-23 15:28 UTC, vovasalyha commented on src/test/java/project/bookstore/service/ShoppingCartServiceTest.java
> +    public void addCartItemToShoppingCart_InValidBookId_ThrowsException() {
```suggestion
    public void addCartItemToShoppingCart_InvalidBookId_ThrowsException() {
```

2023-10-23 15:28 UTC, vovasalyha commented on src/test/java/project/bookstore/service/ShoppingCartServiceTest.java
> +    public void addCartItemToShoppingCart_ReturnsResponseStatusAccepted() {
is it correct name for this test case `ReturnsResponseStatusAccepted`?

2023-10-23 15:28 UTC, vovasalyha commented on src/test/java/project/bookstore/service/ShoppingCartServiceTest.java
> +    public void updateCartItemQuantityById_InValidId_ThrowsException() {
```suggestion
    public void updateCartItemQuantityById_InvalidId_ThrowsException() {
```

2023-10-24 15:44 UTC, vovasalyha approved these changes

2023-10-24 15:45 UTC, merged