Pr4
IvanFadieiev/BookStore pull request #4
Opened 2023-09-07 17:45 UTC by IvanFadieiev

2023-09-11 07:27 UTC, nacenik requested changes
let's improve your solution, and also, fix PR history. a lot of changes from previous PR are shown here.

2023-09-11 07:27 UTC, nacenik commented on src/main/java/project/bookstore/dto/BookRequestDto.java
> +    @Size(min = 13)
try to google about `@ISBN` annotation

2023-09-11 07:27 UTC, nacenik commented on src/main/java/project/bookstore/dto/BookRequestDto.java
> +    @NotNull
could it be an empty string? 
Also [see here](https://www.baeldung.com/java-bean-validation-not-null-empty-blank) and find out a way to use one annotation instead of 2

2023-09-11 07:27 UTC, nacenik commented on src/main/java/project/bookstore/dto/BookRequestDto.java
> +    @NotNull
the same

2023-09-11 07:27 UTC, nacenik commented on src/main/java/project/bookstore/exception/GlobalExceptionHandler.java
> +        body.put("status", HttpStatus.BAD_REQUEST);
should all your exceptions throw 400?

2023-09-12 14:14 UTC, vovasalyha approved these changes
GJ. Take a look on few suggestions

2023-09-12 14:14 UTC, vovasalyha commented on src/main/java/project/bookstore/dto/BookRequestDto.java
>      private String title;
It's also important to set a maximum size of a string to not get an SQL exception because of violating a constraint

2023-09-12 14:14 UTC, vovasalyha commented on src/main/java/project/bookstore/dto/BookRequestDto.java
>      private String author;
same for this field

2023-09-13 09:48 UTC, merged