Pr6 2
IvanFadieiev/BookStore pull request #7
Opened 2023-09-13 10:28 UTC by IvanFadieiev

2023-09-13 19:07 UTC, ArtemReizer approved these changes
LGTM!))

2023-09-14 06:48 UTC, nacenik requested changes
Good solution, let's improve it :)

2023-09-14 06:48 UTC, nacenik commented on pom.xml
> +            <artifactId>swagger-annotations-jakarta</artifactId>
use this artifactId instead `springdoc-openapi-starter-webmvc-ui`

2023-09-14 06:48 UTC, nacenik commented on pom.xml
> +            <version>1.9.4</version>
do you really need this annotation?

2023-09-14 06:48 UTC, nacenik commented on pom.xml
> +                <version>3.3.0</version>
put versions into properties

2023-09-14 06:48 UTC, nacenik commented on src/main/java/project/bookstore/model/User.java
> +    private Set<Role> roles;
do you need this field for toString, equals, and hashcode?

2023-09-14 06:48 UTC, nacenik commented on src/main/java/project/bookstore/service/impl/UserServiceImpl.java
> +            throw new RegistrationException("User with such credentials already exists");
```suggestion
            throw new RegistrationException("User with such email is already exists");
```

2023-09-14 06:48 UTC, nacenik commented on src/main/resources/db/changelog/changes/07-add-users-to-user-role-table.yaml
> +                  value: 1
use sth like this: `valueComputed: (SELECT id FROM users WHERE email = 'admin@email')` instead of hardcode `value: 1`

2023-09-14 18:19 UTC, IvanFadieiev commented on pom.xml
> +            <version>1.9.4</version>
Yes, I need PropertyUtils.geProperty() method in my FieldMatchValidator class

2023-09-15 11:55 UTC, andrii-hoienko requested changes
Better, but some comments are not resolved

2023-09-15 11:55 UTC, andrii-hoienko commented on pom.xml
> +            <version>1.9.4</version>
If so please put versions into properties

2023-09-15 11:55 UTC, andrii-hoienko commented on src/main/java/project/bookstore/validation/FieldMatchValidator.java
> +    private String firstFieldName;
It is not clear what is first and what is second, please think about better names for this fields

2023-09-15 11:55 UTC, andrii-hoienko commented on src/main/java/project/bookstore/security/JwtUtil.java
> +
```suggestion
```

2023-09-15 11:55 UTC, andrii-hoienko commented on src/main/java/project/bookstore/security/JwtAuthentificationFilter.java
> +            return bearerToken.substring(7);
magic number

2023-09-15 11:55 UTC, andrii-hoienko commented on src/main/java/project/bookstore/security/JwtAuthentificationFilter.java
> +        if (StringUtils.hasText(bearerToken) && bearerToken.startsWith("Bearer ")) {
please add constant

2023-09-15 11:55 UTC, andrii-hoienko commented on src/main/java/project/bookstore/security/JwtAuthentificationFilter.java
> +        String bearerToken = request.getHeader("Authorization");
please add constant

2023-09-15 11:55 UTC, andrii-hoienko commented on src/main/java/project/bookstore/config/SecurityConfig.java
> +@EnableWebSecurity
This annotation is redundant

2023-09-15 15:12 UTC, vovasalyha approved these changes

2023-09-15 15:33 UTC, merged