Pr7
IvanFadieiev/BookStore pull request #8
Opened 2023-09-15 09:50 UTC by IvanFadieiev

2023-09-17 07:11 UTC, ivan0dyatlyukkk approved these changes
GJ! 🏎️  However, please, check my suggestions :)

2023-09-17 07:11 UTC, ivan0dyatlyukkk commented on src/main/java/project/bookstore/controller/CategoryController.java
> +    @PreAuthorize("hasRole('ROLE_USER')")
I suggest you to use the hasAnyRole method and specify two roles ('ROLE_USER', 'ROLE_ADMIN') instead of using hasRole.
```suggestion
    @PreAuthorize("hasAnyRole('ROLE_USER', 'ROLE_ADMIN')")
```

2023-09-17 07:11 UTC, ivan0dyatlyukkk commented on src/main/java/project/bookstore/controller/CategoryController.java
> +    @PreAuthorize("hasRole('ROLE_USER')")
```suggestion
@PreAuthorize("hasAnyRole('ROLE_USER', 'ROLE_ADMIN')")
```

2023-09-17 07:11 UTC, ivan0dyatlyukkk commented on src/main/java/project/bookstore/controller/CategoryController.java
> +    @PreAuthorize("hasRole('ROLE_USER')")
```suggestion
    @PreAuthorize("hasAnyRole('ROLE_USER', 'ROLE_ADMIN')")
```

2023-09-19 11:44 UTC, andrii-hoienko requested changes
GJ, I left minor comments

2023-09-19 11:44 UTC, andrii-hoienko commented on src/main/java/project/bookstore/model/Category.java
> +    public Category() {
It is better to use NoArgsConstructor annotation from lombok

2023-09-19 11:44 UTC, andrii-hoienko commented on src/main/resources/db/changelog/changes/08-create-categories-table.yaml
> +      author: ivan
Please specify your name and surname

2023-09-19 11:44 UTC, andrii-hoienko commented on src/main/resources/db/changelog/db.changelog-master.yaml
> +#  - include:
Please dont push commented code on remote

2023-09-19 15:28 UTC, vovasalyha approved these changes

2023-09-19 16:33 UTC, merged