added shopping cart controller logic
IvanFadieiev/BookStore pull request #9
Opened 2023-09-19 12:56 UTC by IvanFadieiev

2023-09-19 19:59 UTC, DmytroV95 requested changes
Good job! Left some recommendations to improve your solution.

2023-09-19 19:59 UTC, DmytroV95 commented on src/main/java/project/bookstore/controller/ShoppingCartController.java
> +    public void deleteBookById(@PathVariable Long id) {
```suggestion
    public void deleteCartItemById(@PathVariable Long id) {
```
Think about using general naming in your code (cartItem instead of book) Personally my recommendation)

2023-09-19 19:59 UTC, DmytroV95 commented on src/main/java/project/bookstore/dto/shoppingcart/CartItemRequestDto.java
> +    private Integer quantity;
Add @NotNull

2023-09-19 19:59 UTC, DmytroV95 commented on src/main/java/project/bookstore/dto/shoppingcart/CartItemUpdateDto.java
> +    @Min(1)
Add @NotNull check.

2023-09-19 19:59 UTC, DmytroV95 commented on src/main/java/project/bookstore/mapper/CartItemMapper.java
> +}
You can also use mapping annotation to do it.

2023-09-19 19:59 UTC, DmytroV95 commented on src/main/java/project/bookstore/mapper/ShoppingCartMapper.java
> +    }
You can also use mapping annotation to do it.

2023-09-19 19:59 UTC, DmytroV95 commented on src/main/java/project/bookstore/model/ShoppingCart.java
> +@Table(name = "shopping_cart")
Use one naming style (You have shopping_cart and cart_items)

2023-09-19 19:59 UTC, DmytroV95 commented on src/main/java/project/bookstore/repository/CartItemsRepository.java
> +    void deleteCartItemById(Long id);
You already have default method deleteById and findById;

2023-09-19 19:59 UTC, DmytroV95 commented on src/main/java/project/bookstore/service/impl/ShoppingCartServiceImpl.java
> +    public void addBooksToShoppingCart(CartItemRequestDto cartItemRequestDto) {
I think it's better to use abstraction naming, like addCartItems... Because in our code you have names cart items and books, I think it's better to use one naming style. Check in all methods if you want)

2023-09-19 19:59 UTC, DmytroV95 commented on src/main/java/project/bookstore/service/impl/ShoppingCartServiceImpl.java
> +    public void updateBookQuantityById(Long id, CartItemUpdateDto cartItemUpdateDto) {
I think you should return updated result of cart item information.

2023-09-19 19:59 UTC, DmytroV95 commented on src/main/java/project/bookstore/service/impl/UserServiceImpl.java
> +        shoppingCart.setUser(savedUser);
Extract the creation of shopping cart operation as a separate method.

2023-09-19 19:59 UTC, DmytroV95 commented on src/main/java/project/bookstore/service/impl/ShoppingCartServiceImpl.java
> +                        new EntityNotFoundException("CardItem with provided id doesn't exists"));
Which id? Add id as parameter to exception message and check others messages to get more information about issue.

2023-09-19 19:59 UTC, DmytroV95 commented on src/main/java/project/bookstore/service/impl/ShoppingCartServiceImpl.java
> +        return dto;
Not informative naming

2023-09-20 13:09 UTC, IvanFadieiev commented on src/main/java/project/bookstore/service/impl/UserServiceImpl.java
> +        shoppingCart.setUser(savedUser);
@DmytroV95 Can you elaborate on this? I already have a separate method for getting the current user's shopping cart, why should I have a separate method for the creation of a shopping cart?

2023-09-20 13:12 UTC, IvanFadieiev commented on src/main/java/project/bookstore/service/impl/ShoppingCartServiceImpl.java
> +    public void updateBookQuantityById(Long id, CartItemUpdateDto cartItemUpdateDto) {
@DmytroV95 In my controller i have @ResponseStatus(HttpStatus.ACCEPTED) annotation. In my opinion, it's enough for user to understand that his cart item was updated.

2023-09-25 08:37 UTC, DmytroV95 approved these changes
GJ!

2023-09-26 15:03 UTC, vovasalyha requested changes
GJ. Let's improve it a bit

2023-10-02 12:56 UTC, andrii-hoienko requested changes
GJ, but some improvements required

2023-10-02 12:56 UTC, andrii-hoienko commented on src/main/java/project/bookstore/model/CartItem.java
> +    private ShoppingCart shoppingCart;
not resolved

2023-10-02 12:56 UTC, andrii-hoienko commented on src/main/java/project/bookstore/service/impl/UserServiceImpl.java
> +                        -> new EntityNotFoundException("User with "
add details to error message

2023-10-02 12:56 UTC, andrii-hoienko commented on src/main/java/project/bookstore/service/impl/ShoppingCartServiceImpl.java
> +        if (cartItem.getShoppingCart().equals(getCurrentShoppingCart())) {
it is better to receive from database entities which already belongs to user, it will remove logic of user checking in all services

2023-10-09 15:53 UTC, vovasalyha approved these changes

2023-10-09 16:11 UTC, merged